In [2]:
import numpy as np
import pandas as pd
import requests
import json

In [77]:
#fetching the data
url = 'https://sih-temper-app.eu-gb.mybluemix.net/getuserdb'   #put the required url
JSONContent = requests.get(url).json()
content = json.dumps(JSONContent, indent = 4, sort_keys = True)

In [78]:
data = JSONContent['table']
data

[['02ecaae0a034d892',
  'Howrah',
  'West Bengal',
  2,
  22.5848,
  88.3271,
  None,
  None,
  None,
  None,
  None],
 ['0d4072140d719390',
  'Jaipur Municipal Corporation',
  'Rajasthan',
  1,
  26.8726,
  75.796,
  None,
  None,
  None,
  None,
  None],
 ['102fdcea95f000a6',
  'Jaipur',
  'Rajasthan',
  3,
  26.7774,
  75.8736,
  4.0,
  2.0,
  6.0,
  2.0,
  14.0],
 ['13a59dfe9fb2b3c1',
  'Shafipur',
  'Uttar Pradesh',
  2,
  28.4729,
  77.482,
  4.0,
  3.0,
  3.0,
  -2.0,
  8.0],
 ['165699385c046a89',
  'Jaipur',
  'Rajasthan',
  3,
  26.7758,
  75.8781,
  2.5,
  1.0,
  0.0,
  -1.0,
  2.5],
 ['18c6c4a4b0a7f31e',
  'Jaipur',
  'Rajasthan',
  3,
  26.7779,
  75.8757,
  2.5,
  3.25,
  0.0,
  -1.0,
  4.75],
 ['1fee591fc1176060',
  'Kolkata',
  'West Bengal',
  2,
  22.4727,
  88.391,
  None,
  None,
  None,
  None,
  None],
 ['23963fa47bed9561',
  'Kolkata',
  'West Bengal',
  1,
  22.5249,
  88.3904,
  4.0,
  0.25,
  6.0,
  2.0,
  12.25],
 ['25353358c65e9599',
  'Ahmedabad',
  'Gujarat',
  1,
  23.0116,
  72.571,
  None,
  None,
  None,
  None,
  None],
 ['2cbca43d1ee3eb73',
  'Kolkata',
  'West Bengal',
  2,
  22.6215,
  88.4079,
  3.0,
  3.0,
  5.0,
  3.0,
  14.0],
 ['2d543c6bed31ca37',
  'Adoor',
  'Kerala',
  2,
  9.16616,
  76.6909,
  4.0,
  0.75,
  3.0,
  2.0,
  9.75],
 ['2dc655aff277b8b4',
  'Kolkata',
  'West Bengal',
  2,
  22.4736,
  88.4126,
  5.0,
  1.75,
  4.0,
  1.0,
  11.75],
 ['31524fae3d1b5f07',
  'Kolkata',
  'West Bengal',
  2,
  22.4751,
  88.4162,
  None,
  None,
  None,
  None,
  None],
 ['3716c2b7bf286dc6',
  'Kolkata',
  'West Bengal',
  2,
  22.475,
  88.417,
  7.0,
  1.25,
  5.0,
  0.0,
  13.25],
 ['3a5c916a017bc499',
  'Bengaluru',
  'Karnataka',
  2,
  13.0407,
  77.6204,
  5.0,
  2.75,
  6.0,
  2.0,
  15.75],
 ['3ce4b6a66ac91787',
  'Bhubaneswar Municipal Corporation',
  'Odisha',
  2,
  20.202,
  85.7966,
  0.5,
  3.0,
  3.0,
  1.0,
  7.5],
 ['3d134e5e5c57572c',
  'Pune',
  'Maharashtra',
  2,
  18.5614,
  73.8837,
  1.0,
  2.0,
  2.0,
  -1.0,
  4.0],
 ['40d238c8db77629e',
  'Greater Noida',
  'Uttar Pradesh',
  2,
  28.4736,
  77.5108,
  5.0,
  2.25,
  5.0,
  2.0,
  14.25],
 ['46165bb065b5f3e8',
  'Jaipur',
  'Rajasthan',
  2,
  26.7771,
  75.8743,
  None,
  None,
  None,
  None,
  None],
 ['478cef7e5379e34a',
  'Kolkata',
  'West Bengal',
  2,
  22.5146,
  88.3653,
  None,
  None,
  None,
  None,
  None],
 ['482552f232c46561',
  'Kolkata',
  'West Bengal',
  2,
  22.4761,
  88.4149,
  None,
  None,
  None,
  None,
  None],
 ['49233a3848e80430',
  'Bengaluru',
  'Karnataka',
  2,
  12.9565,
  77.7217,
  3.0,
  1.5,
  6.0,
  2.0,
  12.5],
 ['49efd35870df5fae',
  'Loni Kalbhor',
  'Maharashtra',
  2,
  18.4806,
  74.0232,
  None,
  None,
  None,
  None,
  None],
 ['4a16cd6a5d5dace8',
  'Kolkata',
  'West Bengal',
  2,
  22.4743,
  88.4139,
  None,
  None,
  None,
  None,
  None],
 ['4bdf0ae7927a7323',
  'Kolkata',
  'West Bengal',
  2,
  22.4909,
  88.3037,
  -3.0,
  0.75,
  5.0,
  -1.0,
  1.75],
 ['4ea430ce5b9ed7c5',
  'Kolkata',
  'West Bengal',
  2,
  22.5066,
  88.4007,
  None,
  None,
  None,
  None,
  None],
 ['4f3cff52755dc3b6',
  'Majitar',
  'Sikkim',
  2,
  27.1832,
  88.5015,
  5.0,
  1.5,
  5.0,
  2.0,
  13.5],
 ['52b91113c2c5994a',
  'Kolkata',
  'West Bengal',
  3,
  22.473,
  88.413,
  None,
  None,
  None,
  None,
  None],
 ['553f8b00ea91fafc',
  'Kolkata',
  'West Bengal',
  2,
  22.4793,
  88.4145,
  None,
  None,
  None,
  None,
  None],
 ['5bacca5bd06eba1c',
  'Kolkata',
  'West Bengal',
  2,
  22.4739,
  88.4187,
  None,
  None,
  None,
  None,
  None],
 ['5f2d2fe91f3add4c',
  'Shafipur',
  'Uttar Pradesh',
  3,
  28.4728,
  77.482,
  -1.0,
  2.75,
  4.0,
  2.0,
  7.75],
 ['6272b8eec169ce63',
  'Bokaro',
  'Jharkhand',
  3,
  23.6664,
  86.1461,
  5.0,
  1.75,
  4.0,
  2.0,
  12.75],
 ['631fe3df45c31fb5',
  'Kolkata',
  'West Bengal',
  2,
  22.4805,
  88.4088,
  None,
  None,
  None,
  None,
  None],
 ['6612d0e30dd3ffde',
  'Mhalunge',
  'Maharashtra',
  2,
  18.5856,
  73.7408,
  5.0,
  1.75,
  6.0,
  2.0,
  14.75],
 ['673209b4d3ea6e46',
  'Kolkata',
  'West Bengal',
  2,
  22.4807,
  88.3654,
  1.0,
  2.5,
  5.0,
  3.0,
  11.5],
 ['695b8fce0faa0122',
  'Bhubaneswar Municipal Corporation',
  'Odisha',
  2,
  20.3474,
  85.8082,
  3.0,
  3.25,
  3.5,
  3.0,
  12.75],
 ['6a37d776d7265459',
  'Ghaziabad',
  'Uttar Pradesh',
  3,
  28.6128,
  77.3721,
  None,
  None,
  None,
  None,
  None],
 ['6a7c263ce55ca347',
  'Maheshtala',
  'West Bengal',
  2,
  22.4868,
  88.3124,
  None,
  None,
  None,
  None,
  None],
 ['6b7041279124b94d',
  'Kolkata',
  'West Bengal',
  2,
  22.607,
  88.4097,
  None,
  None,
  None,
  None,
  None],
 ['7559c9e11704d076',
  'Pune',
  'Maharashtra',
  2,
  18.5666,
  73.878,
  6.0,
  1.75,
  4.0,
  2.0,
  13.75],
 ['77d15c8923805d60',
  'Kolkata',
  'West Bengal',
  2,
  22.5012,
  88.3337,
  7.0,
  2.75,
  3.0,
  2.0,
  14.75],
 ['85470e27177597f3',
  'Kolkata',
  'West Bengal',
  2,
  22.4757,
  88.4146,
  None,
  None,
  None,
  None,
  None],
 ['936a4bda8e6c57d9',
  'Kolkata',
  'West Bengal',
  2,
  22.4786,
  88.4152,
  -2.0,
  2.0,
  2.0,
  0.0,
  2.0],
 ['97621793181447a0',
  'Bengaluru',
  'Karnataka',
  1,
  13.0046,
  77.6539,
  None,
  None,
  None,
  None,
  None],
 ['99033c04eceb1cf7',
  'Kolkata',
  'West Bengal',
  2,
  22.5784,
  88.4198,
  None,
  None,
  None,
  None,
  None],
 ['9eb5a9cbc4063963',
  'Howrah',
  'West Bengal',
  2,
  22.5814,
  88.256,
  -0.5,
  2.25,
  4.5,
  2.0,
  8.25],
 ['a4fc57f979b41a7f',
  'Bengaluru',
  'Karnataka',
  1,
  12.9708,
  77.7178,
  2.0,
  0.5,
  0.5,
  2.0,
  5.0],
 ['a84db894bb955515',
  'Shafipur',
  'Uttar Pradesh',
  1,
  28.4729,
  77.4821,
  3.0,
  0.25,
  2.0,
  -1.0,
  4.25],
 ['aa9d9dbad64cc9dd',
  'Kolkata',
  'West Bengal',
  2,
  22.4752,
  88.4185,
  None,
  None,
  None,
  None,
  None],
 ['aad4c5f51ddf280e',
  'Kolkata',
  'West Bengal',
  2,
  22.4759,
  88.4149,
  None,
  None,
  None,
  None,
  None],
 ['ab376e98fc83bf9c',
  'Kolkata',
  'West Bengal',
  2,
  22.4873,
  88.3511,
  None,
  None,
  None,
  None,
  None],
 ['ab6275a8df171d07',
  'Kolkata',
  'West Bengal',
  2,
  22.473,
  88.4141,
  None,
  None,
  None,
  None,
  None],
 ['b003e5254446fbcc',
  'Kolkata',
  'West Bengal',
  2,
  22.4738,
  88.4135,
  2.0,
  1.25,
  4.0,
  2.0,
  9.25],
 ['bbd86af31fe34948',
  'Kolkata',
  'West Bengal',
  2,
  22.5671,
  88.4053,
  None,
  None,
  None,
  None,
  None],
 ['bbf41961c62c01c3',
  'South Dumdum',
  'West Bengal',
  2,
  22.6242,
  88.3892,
  3.0,
  0.5,
  4.0,
  0.0,
  7.5],
 ['bf6f3747d2a8d354',
  'East Delhi',
  'Delhi',
  2,
  28.626,
  77.2816,
  4.0,
  1.5,
  4.5,
  3.0,
  13.0],
 ['c1b5c085f8ae291b',
  'Kolkata',
  'West Bengal',
  2,
  22.476,
  88.4077,
  4.0,
  2.75,
  4.0,
  2.0,
  12.75],
 ['c2e7e783405e380a',
  'Kolkata',
  'West Bengal',
  1,
  22.4756,
  88.4147,
  None,
  None,
  None,
  None,
  None],
 ['c6c0fdefee36840e',
  'Bengaluru',
  'Karnataka',
  2,
  12.9208,
  77.5958,
  4.0,
  1.5,
  6.0,
  2.0,
  13.5],
 ['cba6e6622e8e5e4e',
  'Kolkata',
  'West Bengal',
  2,
  22.4693,
  88.4044,
  None,
  None,
  None,
  None,
  None],
 ['ce3a8c7dda94774b',
  'Cuttack',
  'Odisha',
  3,
  20.4626,
  85.898,
  0.0,
  1.0,
  3.0,
  0.0,
  4.0],
 ['d089436d3d3e4deb',
  'Hyderabad',
  'Telangana',
  2,
  17.4821,
  78.537,
  4.0,
  0.25,
  5.0,
  2.0,
  11.25],
 ['d65e5f02f5e8757a',
  'Kolkata',
  'West Bengal',
  2,
  22.4803,
  88.415,
  3.5,
  2.0,
  6.0,
  3.0,
  14.5],
 ['d6d5058645fa9b99',
  'Kolkata',
  'West Bengal',
  2,
  22.4722,
  88.4105,
  -1.5,
  1.25,
  1.0,
  3.0,
  3.75],
 ['d6e8e5bc3d7773a7',
  'Nedumbassery',
  'Kerala',
  3,
  10.1556,
  76.3903,
  None,
  None,
  None,
  None,
  None],
 ['d8dffbd739d6c56f',
  'Kolkata',
  'West Bengal',
  2,
  22.4675,
  88.3912,
  4.0,
  2.0,
  6.0,
  2.0,
  14.0],
 ['da597f670ae81448',
  'Kolkata',
  'West Bengal',
  1,
  22.5047,
  88.3049,
  5.0,
  1.75,
  4.0,
  1.0,
  11.75],
 ['daeb90f194bf033c',
  'Jaipur',
  'Rajasthan',
  2,
  26.776,
  75.8775,
  7.0,
  3.25,
  6.0,
  3.0,
  19.25],
 ['e432c34348294226',
  'Kolkata',
  'West Bengal',
  2,
  22.5529,
  88.366,
  6.0,
  1.25,
  4.0,
  2.0,
  13.25],
 ['e756b1c9ae6096e4',
  'Kolkata',
  'West Bengal',
  2,
  22.5497,
  88.3849,
  -2.0,
  2.75,
  3.0,
  2.0,
  5.75],
 ['ec45d6a93d09bf42',
  'Greater Noida',
  'Uttar Pradesh',
  2,
  28.4746,
  77.4773,
  None,
  None,
  None,
  None,
  None],
 ['ef5ee945522cc886',
  'Kolkata',
  'West Bengal',
  2,
  22.4759,
  88.416,
  None,
  None,
  None,
  None,
  None],
 ['ef66a342fff6089d',
  'Chunakkara',
  'Kerala',
  2,
  9.20212,
  76.6483,
  None,
  None,
  None,
  None,
  None],
 ['f23978a26f07577b',
  'Kolkata',
  'West Bengal',
  2,
  22.6616,
  88.4357,
  5.0,
  1.0,
  4.5,
  2.0,
  12.5],
 ['f48b327274f35451',
  'Kolkata',
  'West Bengal',
  2,
  22.4842,
  88.3407,
  5.0,
  1.75,
  3.0,
  3.0,
  12.75],
 ['f69bac5cbef64994',
  'Bokaro',
  'Jharkhand',
  2,
  23.6911,
  86.1719,
  None,
  None,
  None,
  None,
  None],
 ['f79df89a0b43fe08',
  'Muzaffarpur',
  'Bihar',
  2,
  26.0593,
  85.5081,
  None,
  None,
  None,
  None,
  None]]

In [94]:
df = pd.DataFrame(data)
df.columns = ['uid', 'city' , 'state', "age_range_id", "latitude", "longitude", "si_rank", "se_rank","cs_rank","rt_rank","overall_rank"]
df.fillna(0 , inplace =  True)
df.head()

,uid,city,state,age_range_id,latitude,longitude,si_rank,se_rank,cs_rank,rt_rank,overall_rank
0,02ecaae0a034d892,Howrah,West Bengal,2,22.5848,88.3271,0.0,0.0,0.0,0.0,0.0
1,0d4072140d719390,Jaipur Municipal Corporation,Rajasthan,1,26.8726,75.7960,0.0,0.0,0.0,0.0,0.0
2,102fdcea95f000a6,Jaipur,Rajasthan,3,26.7774,75.8736,4.0,2.0,6.0,2.0,14.0
3,13a59dfe9fb2b3c1,Shafipur,Uttar Pradesh,2,28.4729,77.4820,4.0,3.0,3.0,-2.0,8.0
4,165699385c046a89,Jaipur,Rajasthan,3,26.7758,75.8781,2.5,1.0,0.0,-1.0,2.5

In [96]:
# def si_per():
#     value = (df.si_rank/7) * 100
#     return value
# df
df['si_rank'] = df['si_rank'].apply(lambda x: ((x/7) * 100) )
df['se_rank'] = df['se_rank'].apply(lambda y: ((y/4) * 100))
df['cs_rank'] = df['cs_rank'].apply(lambda z : ((z/6) * 100))
df['rt_rank'] = df['rt_rank'].apply(lambda a : ((a/3) * 100))
df['overall_rank'] = df['overall_rank'].apply(lambda b : ((b/20) * 100))
num = df._get_numeric_data()
num[num < 0] = 0
df.head()

,uid,city,state,age_range_id,latitude,longitude,si_rank,se_rank,cs_rank,rt_rank,overall_rank
0,02ecaae0a034d892,Howrah,West Bengal,2,22.5848,88.3271,0.000000,0.0,0.0,0.000000,0.0
1,0d4072140d719390,Jaipur Municipal Corporation,Rajasthan,1,26.8726,75.7960,0.000000,0.0,0.0,0.000000,0.0
2,102fdcea95f000a6,Jaipur,Rajasthan,3,26.7774,75.8736,57.142857,50.0,100.0,66.666667,70.0
3,13a59dfe9fb2b3c1,Shafipur,Uttar Pradesh,2,28.4729,77.4820,57.142857,75.0,50.0,0.000000,40.0
4,165699385c046a89,Jaipur,Rajasthan,3,26.7758,75.8781,35.714286,25.0,0.0,0.000000,12.5